import type { Metadata } from "next";
import localFont from "next/font/local";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";

// Local Satoshi font
const satoshi = localFont({
    src: [
        {
            path: "../fonts/Satoshi-Variable.woff2",
            weight: "300 900",
            style: "normal",
        },
        {
            path: "../fonts/Satoshi-VariableItalic.woff2",
            weight: "300 900",
            style: "italic",
        },
    ],
    variable: "--font-satoshi",
    display: "swap",
});

// Google Roboto Mono font
const robotoMono = Roboto_Mono({
    subsets: ["latin"], // include other subsets if needed
    weight: ["400", "700"],
    variable: "--font-roboto-mono",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html
            className={`${satoshi.variable} ${robotoMono.variable}`}
            lang='en'
        >
            <body className='antialiased bg-black1 text-white1'>
                {children}
            </body>
        </html>
    );
}
